# Generated by Django 4.0.3 on 2022-04-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betweenday',
            old_name='reservations',
            new_name='reservation',
        ),
    ]
