# Generated by Django 4.0.2 on 2022-02-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_guest_alter_reservation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='check_output',
            new_name='check_out',
        ),
    ]
